site_name: Home Lab Wiki
site_description: Design and architecture of my home lab.
site_url: https://homelab.taejupark.com/

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Hardware: hardware.md
  - Architecture: architecture.md
  - Software & Services: services.md
  - Storage & Backups: storage.md
  - Roadmap: roadmap.md

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - js/mermaid-init.js
